### ISSUE TITLE
When Robot is charging, connecting with BLE doesn't make the robot blink

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#689]

**Comment by YannLocatelli** [comment]
The PR #734 gives to the robot the ability to do actions on BLE connection and disconnection.

We discussed as a relevant possibility moving the "blue blink" instruction from the tablet to the robot. Also this solution will be more simple since there will be no need to determine if a command can be executed or not depending on the charge status.

**Comment by ladislas** [comment]
Very good idea!
