### ISSUE TITLE
When ouf of battery, OS keeps restarting

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#768]
Based on Hugo's experience:

## Context:

- the robot is running the OS only (no bootloader)
- the robot is on battery

## Behavior:

when the robot runs out of battery:

- it turns off
- then turns back on displaying the Leka Logo
- then back off again
- and it keeps doing that

## Expected behavior

when the robot runs out of battery:

- it should display an image saying it must be charged before actually running out of battery
- it should not constantly try to restart

## Possible solutions

- display the image
- handle low battery in the OS
- **using the bootloader** might fix the issue, but **tests and confirmation must be provided ⚠**

**Comment by YannLocatelli** [comment]
A relevant issue for debug purpose, but in practice, user will always use the whole firmware (bootloader + os) and the bootloader prevent this case since its job is to prevent the battery life and won't allow the os to use below a certain level.

---

> using the bootloader might fix the issue, but tests and confirmation must be provided ⚠

I am not sure on what is expected here, but an implementation of it can be found in this PR:

* https://github.com/leka/LekaOS/pull/381 : Prevent to fall in OS if battery is "empty"
* https://github.com/leka/LekaOS/pull/564 : Add hysteresis offset to avoid recurrent reboots at limit

---

> Possible solutions
> display the image
> handle low battery in the OS

Already done here:

* https://github.com/leka/LekaOS/pull/615

Maybe level is too low and must be raised to let the user to be notified of it
